name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below so we can reproduce and fix it.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly. What did you expect vs. what actually happened?
      placeholder: "When I run `crewly start`, the dashboard opens but no agents appear..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Run `crewly onboard`
        2. Select "Web Dev Team" template
        3. Run `crewly start`
        4. Click "Start Agents"
        5. Nothing happens
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Output of `node --version`"
      placeholder: "v20.11.0"
    validations:
      required: true

  - type: input
    id: crewly-version
    attributes:
      label: Crewly version
      description: "Output of `crewly --version` or `npm list -g crewly`"
      placeholder: "1.0.6"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: AI Runtime
      description: Which AI CLI are you using?
      multiple: true
      options:
        - Claude Code
        - Gemini CLI
        - Codex (OpenAI)
        - Not applicable

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or error output
      description: Paste any error messages or logs. This will be formatted as code automatically.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, config files, or anything else that might help.
